# -*- coding: utf-8 -*-
"""Naive Bayes classifier to detect Spam and Not Spam in Emails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXNoftqU08KW6zy-v2xI3rXjnnLOeMHA
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# 1. Create a dummy dataset (In reality, you'd load a CSV like the 'SpamAssassin' dataset)
data = {
    'email_text': [
        'Free money now, click here to win',
        'Hi Bob, how about a meeting tomorrow at 10am?',
        'Urgent! Claim your free vacation package',
        'Can you review the project proposal by Friday?',
        'Congratulations! You won a free lottery ticket',
        'Lunch with the team is scheduled for noon'
    ],
    'label': ['spam', 'Not Sam', 'spam', 'Not Sam', 'spam', 'Not Sam'] # 'ham' means Not Spam
}

df = pd.DataFrame(data)

# 2. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df['email_text'],
    df['label'],
    test_size=0.33,
    random_state=42
)

# 3. Feature Extraction (Bag of Words)
# This converts text documents to a matrix of token counts
vectorizer = CountVectorizer()

# Fit the vectorizer to the training data and transform it into numbers
X_train_vectorized = vectorizer.fit_transform(X_train)

# Transform the test data using the vocabulary learned from the training data
X_test_vectorized = vectorizer.transform(X_test)

# 4. Train the Naive Bayes Classifier
classifier = MultinomialNB()
classifier.fit(X_train_vectorized, y_train)

# 5. Make Predictions
predictions = classifier.predict(X_test_vectorized)

# 6. Evaluate the Model
print(f"Accuracy: {accuracy_score(y_test, predictions) * 100:.2f}%\n")
print("Classification Report:")
print(classification_report(y_test, predictions))

# --- Testing it on new emails ---
new_emails = [
    "Hey, let's grab coffee later",
    "Win a free iPhone now!! Urgent!!","Click now to claim your prize!"
]
new_emails_vectorized = vectorizer.transform(new_emails)
new_predictions = classifier.predict(new_emails_vectorized)

print("\nPredictions for new emails:")
for email, prediction in zip(new_emails, new_predictions):
    print(f"'{email}' -> {prediction.upper()}")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Compute confusion matrix
cm = confusion_matrix(y_test, predictions, labels=classifier.classes_)

# Display confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classifier.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

print("\n--- Testing with more new emails ---")

more_new_emails = [
    "Click now to claim your prize!",
    "Meeting reminder for tomorrow morning",
    "Limited time offer! Get rich quick!",
    "Just checking in, hope you're doing well",
    "Your account has been compromised. Verify immediately."
]

more_new_emails_vectorized = vectorizer.transform(more_new_emails)
more_new_predictions = classifier.predict(more_new_emails_vectorized)

print("Predictions for additional new emails:")
for email, prediction in zip(more_new_emails, more_new_predictions):
    print(f"'{email}' -> {prediction.upper()}")