# -*- coding: utf-8 -*-
"""Iris Species Classification using K-Nearest Neighbors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mG7F9zuhBqqJPX41mj4hpgWoSbVV_V0Z
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# 1. Load the dataset
iris = load_iris()
X = iris.data  # Features: sepal/petal dimensions
y = iris.target # Labels: 0 (Setosa), 1 (Versicolor), 2 (Virginica)

# 2. Split into Training (80%) and Testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize and Train the Model
# We'll use K=3 (looking at the 3 nearest neighbors)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# 4. Make Predictions
predictions = knn.predict(X_test)

# 5. Evaluate the Model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy with K=3: {accuracy * 100:.2f}%")

# Predict for a single new flower
# [SepalLength, SepalWidth, PetalLength, PetalWidth]
new_flower = [[5.1, 3.5, 1.4, 0.2]]
prediction = knn.predict(new_flower)
print(f"Predicted Species: {iris.target_names[prediction][0]}")

import matplotlib.pyplot as plt
import seaborn as sns
conf_matrix = confusion_matrix(y_test, predictions)
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris.target_names, yticklabels=iris.target_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for Iris Dataset')
plt.show()